### PR TITLE
Docs: knowledge base prior learning and test documentation

### PR DESCRIPTION
**Pull request by Kyle-Dav**
# Description

Created outcome for prior learning review and example documents for React and Markdown.

Fixes # (issue)

## Type of change
- [x] Documentation (new)

# How Has This Been Tested?

The test documents have been tested through a local installation of Docusaurus.

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Kyle-Dav** [comment]
[Summarize relevant prior knowledge](https://trello.com/c/I9FmanEY/27-summarize-relevant-prior-knowledge)

**Comment by Kyle-Dav** [comment]
[Contribute test/initial documentation (pages) to fill knowledge base](https://trello.com/c/fKmEDXnE/35-contribute-test-initial-documentation-pages-to-fill-knowledge-base)

**Comment by Kyle-Dav** [comment]
[Contribute test/initial documentation (pages) to fill knowledge base](https://trello.com/c/fKmEDXnE/35-contribute-test-initial-documentation-pages-to-fill-knowledge-base)

**Comment by maddernd** [comment]
Markdown lint and prettier errors, please fix and resubmit

**Review by maddernd — APPROVED** [review]

**Pull request merged**
